apiVersion: v1
kind: ConfigMap
metadata:
  name: eshop-config
  namespace: eshop
data:
  # ASPNETCORE_ENVIRONMENT: "Development"
  ConnectionStrings__DefaultConnection: "Server=db;Database=EShopDB;User=sa;Password=$(SA_PASSWORD);"
