apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-app
  namespace: eshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop-app
  template:
    metadata:
      labels:
        app: eshop-app
    spec:
      containers:
        - name: eshop-app
          image: anastasija1701/eshop-app:latest
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eshop-secrets
                  key: SA_PASSWORD
            - name: ConnectionStrings__DefaultConnection
              value: "Server=db;Database=EShopDB;User=sa;Password=$(SA_PASSWORD)"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"

